name: Tagged Release

on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**/*-pre*'

jobs:
  linux-build:
    if: "!contains(github.ref, '-pre')"
    name: "Linux Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout-code"
        uses: actions/checkout@v4
      - name: "get-release-tag"
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: "install uv"
        run: pip install uv
      - name: "Setup project"
        run: uv sync
      - name: "build"
        run: ./scripts/build_addon.sh
      - name: "Upload release"
        uses: actions/upload-artifact@v4
        with:
          name: BlendHeck
          path: ./dist/*.zip

  create-release:
    name: "Create Release"
    needs: [linux-build]
    runs-on: ubuntu-latest
    steps:
      - name: "checkout-code"
        uses: actions/checkout@v4
      - name: "get-release"
        uses: actions/download-artifact@v4
        with:
          name: BlendHeck
          path: ./BlendHeck
      - name: "create-release"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          files: |
            ./BlendHeck/*.zip
      - name: "Get release tag"
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
